name: "Merge Queue Action"
description: "GitHub action to help merge PRs in a queueing manner"
author: "Kanitkorn S."
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "git-merge"
  color: "green"
inputs:
  checks:
    description: "List of checks that can be skipped"
    required: true
    default: "merge-queue,task-list-completed"
