version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:latest

    steps:
      - checkout

      - run:
          name: Failing Test
          command: exit 0

workflows:
  version: 2
  build_workflow:
    jobs:
      - build
