name: merge-queue

on:
  status:
  pull_request:
    types:
      - labeled

jobs:
  merge-queue:
    runs-on: ubuntu-latest
    steps:
      - uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}