name: merge-queue

on:
  status:
  pull_request:
    types:
      - labeled

jobs:
  merge-queue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        env:
          GITHUB_TOKEN: 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
