name: merge-queue

on:
  status:
  pull_request:
    types:
      - labeled

jobs:
  merge-queue:
    runs-on: ubuntu-latest
    steps:
      - uses: GetResQ/resq-merge-bot@main
        with:
          checks: ${{ github.event.inputs.checks }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
