name: merge-queue

on:
  status:
  pull_request:
    types:
      - labeled

jobs:
  merge-queue:
    runs-on: ubuntu-latest
    steps:
      - uses: GetResQ/resq-merge-bot@test_branch_3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
