name: merge-queue

on:
  status:
  pull_request:
    types:
      - labeled

jobs:
  merge-queue:
    runs-on: ubuntu-latest
    steps:
      - uses: GetResQ/resq-merge-bot@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHECKS_TO_SKIP: ${{ fromJSON(vars.CHECKS_TO_SKIP) }}
