name: merge-queue

on:
  check_suite:
    types: [completed]
  pull_request_target:
    types:
      - labeled

jobs:
  merge-queue:
    runs-on: ubuntu-latest
    steps:
      - uses: GetResQ/resq-merge-bot@optional-check-suite-event
        with:
          checks_to_skip: merge-queue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
